// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cevnxxhyctigbfzmradp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNldm54eGh5Y3RpZ2Jmem1yYWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODA5MzcsImV4cCI6MjA2OTc1NjkzN30.PDH06Iix5-_xtPRBqEijDPkbPMsGR9Zs2rOGG6K7Pcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});